<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MEJQHUP" failures="1" tests="1" name="Url Testing" time="19.306" errors="0" timestamp="2021-06-10T14:57:26 IST">
  <testcase classname="Academy.ValidateChefPinDinerLogin" name="validateChefPinDLogin" time="7.116">
    <failure type="java.lang.AssertionError" message="expected [https://dev.chefp.in/diner-homepage] but found [https://dev.chefp.in/diner-homepage1]">
      <![CDATA[java.lang.AssertionError: expected [https://dev.chefp.in/diner-homepage] but found [https://dev.chefp.in/diner-homepage1]
at Academy.ValidateChefPinDinerLogin.validateChefPinDLogin(ValidateChefPinDinerLogin.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateChefPinDLogin -->
</testsuite> <!-- Url Testing -->
